[metadata]
name = wanshi
version = 0.1.1
description = A stand-alone util repo
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/KatherLab/wanshi-utils
project_urls =
    Bug Tracker = https://github.com/KatherLab/wanshi-utils/issues
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
packages = find:
python_requires = >=3.8
install_requires =
    matplotlib~=3.10
    numpy~=2.2.5
    openpyxl~=3.1
    pandas~=2.2
    scipy~=1.15
    scikit-learn~=1.6
    tqdm~=4.67
    pytest~=7.4
